[package]
name = "absolutus_rex"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
log = "0.4.17"
pretty_env_logger = "0.4.0"
